version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron-i18n
    versions:
    - 1.2782.0
    - 1.2786.0
    - 1.2792.0
    - 1.2796.0
    - 1.2800.0
    - 1.2802.0
    - 1.2806.0
    - 1.2811.0
    - 1.2815.0
    - 1.2820.0
    - 1.2824.0
    - 1.2827.0
    - 1.2833.0
    - 1.2835.0
    - 1.2839.0
    - 1.2844.0
    - 1.2848.0
    - 1.2854.0
    - 1.2858.0
    - 1.2861.0
    - 1.2863.0
    - 1.2866.0
    - 1.2873.1
    - 1.2875.0
    - 1.2879.0
    - 1.2882.0
    - 1.2889.0
    - 1.2894.0
    - 1.2898.0
    - 1.2901.0
    - 1.2906.0
    - 1.2913.0
    - 1.2917.0
    - 1.2920.0
    - 1.2924.0
    - 1.2928.0
    - 1.2931.0
    - 1.2934.0
    - 1.2938.0
    - 1.2943.0
    - 1.2946.0
    - 1.2950.1
    - 1.2956.0
    - 1.2966.0
    - 1.2967.0
    - 1.2968.0
    - 1.2969.0
    - 1.2970.0
    - 1.2971.0
    - 1.2972.0
    - 1.2973.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: print-js
    versions:
    - 1.5.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
